Feature/desenho git flow
beerandcodeteam/paymentgateway pull request #9
Opened 2020-07-30 22:49 UTC by lamarques

# Release Notes
- Adição do documento de git flow
- Adição do diagrama do git flow

2020-07-30 23:24 UTC, atiladelcanton approved these changes

2020-07-30 23:52 UTC, devatreides requested changes
Só algumas sugestões com relação ao texto. Mas achei o texto interessante no geral.

2020-07-30 23:52 UTC, tombenevides commented on WORK-FLOW.md
> +    *É válido abrir Pull Request das tasks para a feature para efetuar um primeiro code review nessa faze da implementação
"nessa **fase** da implementação..", e não *faze*.

2020-07-30 23:52 UTC, tombenevides commented on WORK-FLOW.md
> +<img src="./Documents/git-flow-payment-gateway.png" alt="Diagrama de git flow" style="width: 80%; margin-right: 10%;" />
Acho que seria interessante diminuir as dimensões da imagem pra facilitar a visualização do diagrama.

2020-07-31 12:34 UTC, atiladelcanton commented on WORK-FLOW.md
> +    *É válido abrir Pull Request das tasks para a feature para efetuar um primeiro code review nessa faze da implementação
@tombenevides fiz o ajuste no texto, caso queria revisar!

2020-07-31 12:35 UTC, atiladelcanton commented on WORK-FLOW.md
> +<img src="./Documents/git-flow-payment-gateway.png" alt="Diagrama de git flow" style="width: 80%; margin-right: 10%;" />
@tombenevides , joguei o width para 60%, acredito que não devemos diminuir muito para não dificultar a leitura!

2020-07-31 13:15 UTC, devatreides requested changes
Acredito que o redimensionamento da imagem ainda seja um problema.

2020-07-31 13:15 UTC, tombenevides commented on WORK-FLOW.md
> +<img src="./Documents/git-flow-payment-gateway.png" alt="Diagrama de git flow" width="60%" style="margin-right: 10%;" />
Ainda ta muito grande.. veja que apesar dos softwares abrirem a imagem de forma compactada, no broswer (que acredito que seja a intenção deste documento, quebra muito a página. A idéia é que a imagem caiba espaço da página, justamente pra facilitar a visualização.

![DeepinScreenshot_select-area_20200731090749](https://user-images.githubusercontent.com/18440704/89037909-5ad27900-d30d-11ea-9c33-eca943372f9d.png)

Deixo aqui uma sugestões de dimensão para a imagem:
![DeepinScreenshot_select-area_20200731091238](https://user-images.githubusercontent.com/18440704/89038299-198e9900-d30e-11ea-84b4-f33813ecd9f0.png)

![git-flow-7-638](https://user-images.githubusercontent.com/18440704/89038338-290de200-d30e-11ea-8968-fe5c31b328d7.jpg)

2020-08-01 18:43 UTC, lamarques commented on WORK-FLOW.md
> +<img src="./Documents/git-flow-payment-gateway.png" alt="Diagrama de git flow" width="60%" style="margin-right: 10%;" />
Bem melhor com a sua imagem, @tombenevides

2020-08-01 19:14 UTC, devatreides approved these changes

2020-08-03 16:35 UTC, lamarques commented on WORK-FLOW.md
> +<img src="./Documents/git-flow-payment-gateway.png" alt="Diagrama de git flow" style="width: 80%; margin-right: 10%;" />
Foi resolvido com a imagem do tom

2020-08-03 18:28 UTC, fsrocha-dev approved these changes

2020-08-03 18:33 UTC, merged